name: test

on:
  push:
    branches:
      "master"
    paths:
      - "bin/**"
  pull_request:
    branches:
      - "master"
    paths:
      - "bin/**"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    container: koalaman/shellcheck:stable
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      run: |
        shellcheck bin/kubectl
